import express from "express";
import productRoutes from "./routes/products.routes.js";
import categoryRoutes from "./routes/categories.routes.js";
import collectionRoutes from "./routes/collections.routes.js";
import colorRoutes from "./routes/colors.routes.js";
import imageRoutes from "./routes/images.routes.js";
import sizeRoutes from "./routes/sizes.routes.js";
import userRoutes from "./routes/users.routes.js";
import cartRoutes from "./routes/carts.routes.js";
import styleRoutes from "./routes/styles.routes.js";
import cartItemsRoutes from "./routes/cartItems.routes.js";
import orderRoutes from "./routes/order.routes.js";
import cors from "cors";
const app = express();
//middlewares
app.use(express.json());
app.use(cors());
app.use(productRoutes);
app.use(colorRoutes);
app.use(categoryRoutes);
app.use(collectionRoutes);
app.use(imageRoutes);
app.use(sizeRoutes);
app.use(userRoutes);
app.use(cartRoutes);
app.use(styleRoutes);
app.use(cartItemsRoutes);
app.use(orderRoutes);
export default app;
